powerdata <- read.table("C:/Users/User/Desktop/household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep =";"  )
subsetdata <- subset(powerdata, Date == "1/2/2007" | Date =="2/2/2007")
globalActivePower <- as.numeric(subsetdata$Global_active_power)
png("plot1.png", width=480, height=480)
hist(globalActivePower, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)",ylab="Frequency")
dev.off() 